name: Build Game

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir ~/haxelib
        haxelib setup ~/haxelib
        haxelib install lime
        haxelib install openfl

    - name: Create OpenFL project
      run: |
        openfl create project Game
        cd Game
        mkdir -p Source/scenes
        echo '<scene background="#FFFFFF" name="MainScene"><text x="100" y="100" font="arial" size="32" color="#000000">Hello, World!</text></scene>' > Source/scenes/MainScene.xml

    - name: Build APK
      run: lime build android

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: My Game APK
        path: MyApp/bin/android/bin/MyApp-release.apk
